import "./globals.css";

export const metadata = {
  title: "BIOARECA",
  description: "Generated by create next app",
  icons: {
    icon: "/arecalogos.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
